### ISSUE TITLE
是该说册爷优秀好，还是美团真闲好呢？

### ISSUE THREAD

**Issue by iohub** [ce39906/self-practices#1]
震惊。好多ML的，最近我要上个GPU了。

**Comment by ce39906** [comment]
这个原本是个老仓库，因为里面有几个代码文件头的 email 是公司的email，被公司安全部门的点名要求删除了，所以重新弄了这个仓库。险些进入阳光刑场，心慌慌

**Comment by iohub** [comment]
这波操作666，骚气十足
